In [2]:
import numpy as np
import pandas as pd
import scipy.optimize as opt
import matplotlib
import matplotlib.pyplot as plt
%matplotlib inline


In [3]:
def get_d_oa(f_a, d_ia):
    return (f_a * d_ia) / (d_ia - f_a)

def get_d_ib(d_ab, d_oa):
    return d_ab - d_oa

def get_f_b(d_ob, d_ib):
    return (d_ob * d_ib) / (d_ib + d_ob)


In [4]:
d_ob = np.array([7.2, 5.0, 11.0])
d_ia = np.array([26.7, 28.5, 22.3])
f_a = np.array([17.5, 17.5, 17.5])
d_ab = np.array([37.7, 38.1, 38.2])

d_oa = get_d_oa(f_a, d_ia)
d_ib = get_d_ib(d_ab, d_oa)
f_b = get_f_b(d_ob, d_ib)


In [5]:
f_b

array([16.00428281, 16.15618661, 14.76922578])

In [6]:
d_oa

array([50.78804348, 45.34090909, 81.30208333])

In [7]:
d_ib

array([-13.08804348,  -7.24090909, -43.10208333])

In [8]:
np.std(f_b) / np.sqrt(3)

0.3586033094578286

In [9]:
np.mean(f_b)

15.64323173436154

In [12]:
np.std([15.3,15.4,15.4]) / np.sqrt(3)

0.02721655269759077

In [15]:
np.std([15.3,15.4,15.4, 16,16.2,14.8]) / np.sqrt(6)

0.18917462048868228