In [1]:
import numpy as np
import pandas as pd
import scipy.optimize as opt
import matplotlib
import matplotlib.pyplot as plt
%matplotlib inline


In [14]:
d_o = np.array([50.0, 45.0, 40.0, 35.0, 30.0, 25.0, 20.0])
d_i = np.array([22.1, 23.0, 25.4, 27.3, 30.9, 39.0, 65.3])

x = 1 / d_o
y = 1 / d_i

def lin_fit(x, b):
    return -x + b
h_o = 1.54
n_oerr = 0.005
h_i = np.array([0.66, 0.79, 0.94, 1.18, 1.54, 2.32, 4.88])



In [6]:
# Does the fit
init_params=[0]
lin_opt, lin_cov = opt.curve_fit(lin_fit, x, y, p0=init_params)

# Best fit values
b = lin_opt
db = np.sqrt(np.diag(lin_cov))


In [7]:
lin_cov

array([[3.11875013e-08]])

In [10]:
b

array([0.06531024])

In [11]:
1/b

array([15.31153561])

In [13]:
db / b ** 2

array([0.04140262])

In [17]:
np.average(h_i / h_o)

1.1419294990723563

In [18]:
np.std(h_i / h_o) / np.sqrt(len(h_i))

0.33774497085550076

In [19]:
np.average(d_i/d_o)

1.1747301587301588

In [20]:
np.std(d_i / d_o) / np.sqrt(len(d_i))

0.3488468451472401

In [22]:
2 * np.sqrt(.34**2+.35**2)

0.9759098319004682

In [27]:
2 * np.sqrt(.04**2 + .25**2)

0.5063595560468865

In [29]:
np.cov(y)

array(0.00011231)

In [30]:
np.corrcoef(x, y)

array([[ 1.        , -0.99908214],
       [-0.99908214,  1.        ]])